configfile:
  - defaults/parameters.yaml
  - omicron_profiles/omicron/builds.yaml

cores: 2
keep-going: False
printshellcmds: True
show-failed-logs: True
restart-times: 2
reason: True
stats: stats.json
set-threads: tree=2
